Repository jekyll/jekyll-sass-converter, pull requests merged in 2019-08, with the labels that each got.

#79 Generate Sass Sourcemaps
  README.md
  lib/fake-sass.rb
  lib/jekyll-sass-converter.rb
  lib/jekyll/converters/scss.rb
  lib/jekyll/source_map_page.rb
  spec/sass_converter_spec.rb
  spec/scss_converter_spec.rb
Labels: feature

#89 Fix rendering of sourcemap page
  lib/jekyll/converters/scss.rb
  lib/jekyll/source_map_page.rb
Labels: fix

#88 Release: 2.0.0.pre.beta
  .travis.yml
  History.markdown
  lib/jekyll-sass-converter/version.rb
Labels: release

#86 Use and test sassc-2.1.0 pre-releases and beyond
  jekyll-sass-converter.gemspec
  spec/sass_converter_spec.rb
Labels: dependency
